# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: GamerNoTitle
subtitle: 永远相信 美好的事情 即将发生 Always believe that good things will happen!
description: 欢迎来到GamerNoTitle的网站！如果你喜欢本网站，请支持我！^_^
keywords: [GamerNoTitle,Blog,喵呜初音,bili33,个人博客,程序员,高中生,Python,batch,Github]
author: GamerNoTitle
language: zh-cn
timezone:
email: admin@bili33.top

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://bili33.top
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map: category
tag_map: tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Butterfly@2.2.5

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo: git@github.com:GamerNoTitle/GamerNoTitle.github.io.git

Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml

# hexo-helper-live2d
live2d:
  enable: true
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-tororo  #模板目录，在node_modules里
  display:
    position: right
    width: 150 
    height: 300
  mobile:
    show: false  #是否在手机进行显示

# RSS订阅
plugin:
- hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

# 哔哩哔哩追番
bangumi:
  enable: true
  vmid: 44666814
  title: '追番列表'
  quote: 'TECH OTAKUS SAVE THE WORLD —— MiHoYo'
  show: 1
  loading: 'http://bili33.top/img/bangumi-loading.gif'

# Steam游戏页面
steam:
  enable: true
  steamId: '76561198309889674' #steam 64位Id
  title: Steam游戏库
  quote: '今天G胖又赚了多少？'
  tab: recent
  length: 1000
  imgUrl: 
  proxy:
    host: 127.0.0.1
    port: 10809

# 音乐播放器
aplayer:
  meting: true