# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: GamerNoTitle
subtitle: 永远相信 美好的事情 即将发生 Always believe that good things will happen!
description: 欢迎来到GamerNoTitle的网站！如果你喜欢本网站，请支持我！^_^
keywords: GamerNoTitle,Blog,bili33,个人博客,程序员,高中生,Python,Github
author: GamerNoTitle
language: zh-cn
timezone:
email: admin@bili33.top

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://bili33.top
root: /
permalink: posts/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - 404.html
  - 404css/
  - 404js/
  - BB/BB.html
  - README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
# external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map: category
tag_map: tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Butterfly@3.6.2

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
- type: git
  repo: git@github.com:GamerNoTitle/GamerNoTitle.github.io.git
- type: baidu_url_submitter
- type: cjh_google_url_submitter
# - type: cjh_bing_url_submitter
- type: cjh_baidu_url_submitter

Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml

# hexo-helper-live2d
live2d:
  enable: true
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-tororo  #模板目录，在node_modules里
  display:
    position: right
    width: 150 
    height: 300
  mobile:
    show: false  #是否在手机进行显示

# RSS订阅
plugin:
- hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

# 哔哩哔哩追番
bangumi:
  enable: true
  vmid: 44666814
  title: '追番列表'
  quote: 'TECH OTAKUS SAVE THE WORLD —— MiHoYo'
  show: 1
  loading: 'http://bili33.top/img/bangumi-loading.gif'

# Steam游戏页面
steam:
  enable: true
  steamId: '76561198309889674' #steam 64位Id
  title: Steam游戏库
  quote: '今天G胖又赚了多少？'
  tab: recent
  length: 1000
  imgUrl: 
  proxy:
    host: 127.0.0.1
    port: 10809

# 音乐播放器
aplayer:
  meting: true

#设置百度主动推送
baidu_url_submit:
  count: 10000  #比如200，代表提交最新的200个链接
  host: https://bili33.top # 在百度站长平台中注册的域名，这个改为你自己的域名
  token: 7l6C3M9GqkMItUAt # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里，这个默认

hexo_submit_urls_to_search_engine:
  submit_condition: count #链接被提交的条件，可选值：count | period 现仅支持count
  count: 50 # 提交最新的10个链接
  period: 3600 # 提交修改时间在 900 秒内的链接
  google: 0 # 是否向Google提交，可选值：1 | 0（0：否；1：是）
  bing: 1 # 是否向bing提交，可选值：1 | 0（0：否；1：是）
  baidu: 1 # 是否向baidu提交，可选值：1 | 0（0：否；1：是）
  txt_path: submit_urls.txt ## 文本文档名， 需要推送的链接会保存在此文本文档里
  baidu_host: https://bili33.top ## 在百度站长平台中注册的域名
  baidu_token: 7l6C3M9GqkMItUAt ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  bing_host: http://bili33.top ## 在bing站长平台中注册的域名
  bing_token: 3a9fd2ded9d34dabacca344a3d9f250c ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  google_host: https://bili33.top ## 在google站长平台中注册的域名
  google_key_file: Project.json #存放google key的json文件，放于网站根目录（与hexo _config.yml文件位置相同），请不要把json文件内容直接发布在公众仓库里!
  replace: 0  # 是否替换链接中的部分字符串，可选值：1 | 0（0：否；1：是）
  find_what: https://bili33.top
  replace_with: https://bili33.top