npm install bluebird@^3.7.2 --save
npm install browserify@^17.0.0 --save
npm install cheerio@^1.0.0-rc.12 --save
npm install cuid@^2.1.8 --save
npm install gitalk@^1.8.0 --save
npm install hexo@^7.2.0 --save
npm install hexo-baidu-url-submit@^0.0.6 --save
npm install hexo-bilibili-bangumi@^1.9.0 --save
npm install hexo-butterfly-extjs@^1.4.11 --save
npm install hexo-cli@^4.3.2 --save
npm install hexo-deployer-git@^4.0.0 --save
npm install hexo-generator-archive@^2.0.0 --save
npm install hexo-generator-baidu-sitemap@^0.1.9 --save
npm install hexo-generator-category@^2.0.0 --save
npm install hexo-generator-feed@^3.0.0 --save
npm install hexo-generator-index@^3.0.0 --save
npm install hexo-generator-index-pin-top@^0.2.2 --save
npm install hexo-generator-indexed@^1.2.1 --save
npm install hexo-generator-search@^2.4.3 --save
npm install hexo-generator-sitemap@^3.0.1 --save
npm install hexo-generator-tag@^2.0.0 --save
npm install hexo-renderer-ejs@^2.0.0 --save
npm install hexo-renderer-jade@^0.4.0 --save
npm install hexo-renderer-marked@^6.3.0 --save
npm install hexo-renderer-pug@^3.0.0 --save
npm install hexo-renderer-stylus@^3.0.1 --save
npm install hexo-server@^3.0.0 --save
npm install hexo-steam-games@^1.3.2 --save
npm install hexo-submit-urls-to-search-engine@^2.1.0 --save
npm install hexo-tag-aplayer@^3.0.4 --save
npm install hexo-tag-steamgame@^1.0.0 --save
npm install hexo-util@^3.3.0 --save
npm install hexo-wordcount@^6.0.1 --save
npm install js-yaml@^4.1.0 --save
npm install node-snackbar@^0.1.16 --save
npm install sweetalert@^2.1.2 --save
npm install sweetalert2@^11.11.1 --save