name: Hexo Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "GamerNoTitle@outlook.com"
          git config --global user.name "GamerNoTitle"
          git config --global init.defaultBranch master
          npm install hexo-cli -g
          npm install
          npm install hexo-butterfly-extjs --save
          hexo -v
      - name: Deploy
        run: |
          hexo clean
          hexo b -u
          hexo st -u
          hexo d -g --message "Deploy with Github Action"
